#!/bin/bash
curl -XPOST 'localhost:9200/i_item/item/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
    "bool": {
	      "must": [ 
                  {"term": {"i_manager_id":20}},
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "store_sales",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"term" : {"store_sales.date.d_moy":11}},
				  {"term" : {"store_sales.date.d_year":2001}},
		{"term": {"store_sales.customer.ca_zip":35709}} 
                ]
               }
              }
            }
          }
        }
      }
    }
  }]}}}},
  "aggs": {
   		 "group_by_brand": {
     		 "terms": {
      		  "field": "i_brand",
            "order" : { "_term" : "asc" }
            },
            "aggs": {
   		 	"group_by_brand_id": {
     		 	"terms": {
      		 	 "field": "i_brand_id",
            "order" : { "_term" : "asc" }
      		         },
					  "aggs": {
   		 	"group_by_manufact_id": {
     		 	"terms": {
      		 	 "field": "i_manufact_id",
            "order" : { "_term" : "asc" }
      		         },
					 "aggs": {
   		 	"group_by_manufact": {
     		 	"terms": {
      		 	 "field": "i_manufact",
            "order" : { "_term" : "asc" }
      		         },
   "aggs": {
    "store_sales": {
      "nested": {
        "path": "store_sales"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"term" : {"store_sales.date.d_moy":11}},
				  {"term" : {"store_sales.date.d_year":2001}},
		          {"term": {"store_sales.customer.ca_zip":35709}} 
                ]
               }
			   },
			"aggs": {
    			"ext_price": {
    			  "sum": {
     		        "field": "store_sales.ss_ext_sales_price"
         }}}}}}}
       }
     }
   }
  }
        }
		}
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/item/resultados/query3.txt
