#!/bin/bash
curl -XPOST 'localhost:9200/i_customer_tpc/customer/_search?pretty' -d '
{
  "query": {"filtered":{ "filter":{
  "bool": {
	      "must": [
		{"bool":{"should":[{"bool":{"must":[{"term": {"hd_dep_count":1}},{"range": {"hd_vehicle_count":{"lte":3}}}]}},
    {"bool":{"must":[{"term": {"hd_dep_count":2}},{"range": {"hd_vehicle_count":{"lte":4}}}]}},
    {"bool":{"must":[{"term": {"hd_dep_count":3}},{"range": {"hd_vehicle_count":{"lte":5}}}]}}]}},
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "store_sales",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
				{"term": {"store_sales.s_store_name":"ese"}},
                  {"term": {"store_sales.time.t_hour":8}},
				   {"range": {"store_sales.time.t_minute":{"gte":30}}}  
                ]
               }
              }
            } 
      }
    }
   }}}]}}}},
   "aggs": {
    "store_sales": {
      "nested": {
        "path": "store_sales"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                 {"term": {"store_sales.s_store_name":"ese"}},
                  {"term": {"store_sales.time.t_hour":8}},
				   {"range": {"store_sales.time.t_minute":{"gte":30}}}     
                ]
               }
			   }
        }
		}
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/customer/resultados/query9.txt
