#!/bin/bash
curl -XPOST 'localhost:9200/i_store_sales/store_sales/_search?pretty' -d '
{
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [
                 {"match" : {"s_city":"Midway"}},
                  {"range": {"date.d_year":{"gte":1999,"lte":2001}}},
				        {"range": {"date.d_dom":{"gte":20,"lte":21}}}, 
		{"bool":{"should":[{"match": {"customer.hd_dep_count":4}},{"match": {"customer.hd_vehicle_count":2}}]}}  
                ]
               }
			   },
   "aggs": {
   		 "group_by_lastname": {
     		 "terms": {
      		  "field": "customer.c_last_name",
            "order" : { "_term" : "asc" }, "size": 100000
            },
			"aggs": {
   		 "group_by_firstname": {
     		 "terms": {
      		  "field": "customer.c_first_name",
            "order" : { "_term" : "asc" }, "size": 100000
            },
			"aggs": {
   		 "group_by_cacity": {
     		 "terms": {
      		  "field": "customer.ca_city",
            "order" : { "_term" : "asc" }, "size": 100000
            },
			   "aggs": {
   		 "group_by_ticket": {
     		 "terms": {
      		  "field": "ss_ticket_number",
            "order" : { "_term" : "asc" }, "size": 100000
            },
			"aggs": {
    			"extended_price": {
    			  "sum": {
     		        "field": "ss_ext_sales_price"
         }}}
   }
  }
        }
		}}}}}
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/store_sales/resultados/query6.txt
