#!/bin/bash
curl -XPOST 'localhost:9200/i_store_sales/store_sales/_search?pretty' -d '
{
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"terms": {"item.i_category":["Music","Home","Sports"]}},
                  {"range" : {"date.d_month_seq":{"gte":1200, "lte":1211}}}
                ]
               }
			   },
          "aggs": {
   		 "group_by_item_id": {
     		 "terms": {
      		  "field": "item.i_item_id",
            "order" : { "_term" : "asc" }, "size": 100000
            },
            "aggs": {
   		 	"group_by_desc": {
     		 	"terms": {
      		 	 "field": "item.i_item_desc",
            "order" : { "_term" : "asc" }
      		         },
					  "aggs": {
   		 	"group_by_category": {
     		 	"terms": {
      		 	 "field": "item.i_category",
            "order" : { "_term" : "asc" }
      		         },
					 "aggs": {
   		 	"group_by_class": {
     		 	"terms": {
      		 	 "field": "item.i_class",
            "order" : { "_term" : "asc" }
      		         },
					 "aggs": {
   		 	"group_by_price": {
     		 	"terms": {
      		 	 "field": "item.i_current_price",
            "order" : { "_term" : "asc" }
      		         },
			"aggs": {
    			"itemrevenue": {
    			  "sum": {
     		        "field": "ss_ext_sales_price"
         }}}}}}}}}
       }
     }
   }
  }
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/store_sales/resultados/query5.txt
