#!/bin/bash
curl -XPOST 'localhost:9200/i_store_sales/store_sales/_search?pretty' -d '
{
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"bool":{"should":[{"bool":{"must":[{"terms": {"item.i_category":["Music","Home","Sports"]}},{"terms": {"item.i_class":["country","rugs","fishing"]}}]}},{"bool":{"must":[{"terms": {"item.i_category":["Women","Men","Children"]}},{"terms": {"item.i_class":["swimwear","shirts","pants"]}}]}}]}}, 
                  {"match" : {"date.d_year":2000}}
                ]
               }
			   },
          "aggs": {
   		 "group_by_category": {
     		 "terms": {
      		  "field": "item.i_category",
            "order" : { "_term" : "asc" }, "size": 100000
            },
            "aggs": {
   		 	"group_by_class": {
     		 	"terms": {
      		 	 "field": "item.i_class",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
					  "aggs": {
   		 	"group_by_brand": {
     		 	"terms": {
      		 	 "field": "item.i_brand",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
					 "aggs": {
   		 	"group_by_store_name": {
     		 	"terms": {
      		 	 "field": "s_store_name",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
					 "aggs": {
   		 	"group_by_company": {
     		 	"terms": {
      		 	 "field": "s_company_name",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
                   "aggs": {
   		 	"group_by_moy": {
     		 	"terms": {
      		 	 "field": "date.d_moy",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
			"aggs": {
    			"sum_sales": {
    			  "sum": {
     		        "field": "ss_sales_price"
         }}}}}}}}}}}
       }
     }
   }
  }
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/store_sales/resultados/query10.txt
