#!/bin/bash
curl -XPOST 'localhost:9200/i_store_sales/store_sales/_search?pretty' -d '
{
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                 {"range": {"s_number_employees":{"gte":200,"lte":295}}},
                  {"range": {"date.d_year":{"gte":1998,"lte":2000}}},
				   {"match": {"date.d_dow":1}},    
		{"bool":{"should":[{"match": {"customer.hd_dep_count":5}},{"range": {"customer.hd_vehicle_count":{"gt":2}}}]}}
                ]
               }
			   },
			   "aggs": {
   		 "group_by_ticket": {
     		 "terms": {
      		  "field": "ss_ticket_number",
            "order" : { "_term" : "asc" }, "size": 100000
            },
            "aggs": {
   		 "group_by_customer": {
     		 "terms": {
      		  "field": "ss_customer_sk",
            "order" : { "_term" : "asc" }, "size": 100000
            },
             "aggs": {
   		 "group_by_s_city": {
     		 "terms": {
      		  "field": "s_city",
            "order" : { "_term" : "asc" }, "size": 100000
            },
			"aggs": {
    			"amt": {
    			  "sum": {
     		        "field": "ss_coupon_amt"
         }}}}}}}
   }
  }
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/store_sales/resultados/query8.txt
