#!/bin/bash
curl -XPOST 'localhost:9200/i_store_sales/store_sales/_search?pretty' -d '
{
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"match": {"item.i_manufact_id":600}},
                  {"match" : {"date.d_moy":12}}
                ]
               }
			   },
          "aggs": {
   		 "group_by_year": {
     		 "terms": {
      		  "field": "date.d_year",
            "order" : { "_term" : "asc" }
            },
            "aggs": {
   		 	"group_by_brand": {
     		 	"terms": {
      		 	 "field": "item.i_brand",
            "order" : { "_term" : "asc" }
      		         },
					  "aggs": {
   		 	"group_by_brand_id": {
     		 	"terms": {
      		 	 "field": "item.i_brand_id",
            "order" : { "_term" : "asc" }
      		         },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "ss_sales_price"
         }}}}}
       }
     }
   }
  }
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/store_sales/resultados/query1.txt
