#!/bin/bash
curl -XPOST 'localhost:9200/i_store_sales/store_sales/_search?pretty' -d '
{
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"match": {"item.i_manager_id":1}},
                  {"match" : {"date.d_moy":11}},
				  {"match" : {"date.d_year":2001}},
				  {"bool":{"should":[{"match": {"time.t_meal_time":"breakfast"}},{"match": {"time.t_meal_time":"dinner"}}]}}
                ]
               }
			   },
            "aggs": {
   		 	"group_by_brand": {
     		 	"terms": {
      		 	 "field": "item.i_brand",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
					  "aggs": {
   		 	"group_by_brand_id": {
     		 	"terms": {
      		 	 "field": "item.i_brand_id",
            "order" : { "_term" : "asc" }
      		         },
					  "aggs": {
   		 	"group_by_hour": {
     		 	"terms": {
      		 	 "field": "time.t_hour",
            "order" : { "_term" : "asc" }
      		         },
					 "aggs": {
   		 	"group_by_minute": {
     		 	"terms": {
      		 	 "field": "time.t_minute",
            "order" : { "_term" : "asc" }
      		         },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "ss_ext_sales_price"
         }}}}}}}
       }
     }
   }
  }
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/store_sales/resultados/query7.txt
