#!/bin/bash
curl -XPOST 'localhost:9200/i_store_sales/store_sales/_search?pretty' -d '
{ 
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ {"match" : {"s_state":"TN"}},
                  {"match": {"date.d_year":2001}}, 
		{"match": {"customer.cd_gender":"F"}},{"match": {"customer.cd_marital_status":"S"}},{"match": {"customer.cd_education_status":"Secondary"}}
                ]
               }
			   },
          "aggs": {
   		 "group_by_item_id": {
     		 "terms": {
      		  "field": "item.i_item_id",
            "order" : { "_term" : "asc" }, "size": 100
            },
            "aggs": {
   		 	"group_by_s_state": {
     		 	"terms": {
      		 	 "field": "s_state",
            "order" : { "_term" : "asc" }
      		         },
			"aggs": {
    			"agg4": {
    			  "sum": {
     		        "field": "ss_sales_price"
         }}}
       }
     }
   }
  }
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/store_sales/resultados/query4.txt
