#!/bin/bash
curl -XPOST 'localhost:9200/i_time/time/_search?pretty' -d '
{
  "query": {"filtered": {
      "filter": {
   "bool": {
	      "must": [
				  {"terms": {"t_meal_time":["breakfast","dinner"]}},
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "store_sales",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"term": {"store_sales.item.i_manager_id":1}},
                  {"term" : {"store_sales.date.d_moy":11}},
				  {"term" : {"store_sales.date.d_year":2001}}
                ]
               }
              }
            }
          }
        }
      }
    }
  }]}}}},
					  "aggs": {
   		 	"group_by_hour": {
     		 	"terms": {
      		 	 "field": "t_hour",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
					 "aggs": {
   		 	"group_by_minute": {
     		 	"terms": {
      		 	 "field": "t_minute",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
   "aggs": {
    "lineorder": {
      "nested": {
        "path": "store_sales"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"term": {"store_sales.item.i_manager_id":1}},
                  {"term" : {"store_sales.date.d_moy":11}},
				  {"term" : {"store_sales.date.d_year":2001}}
                ]
               }
			   },
            "aggs": {
   		 	"group_by_brand": {
     		 	"terms": {
      		 	 "field": "store_sales.item.i_brand",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
					  "aggs": {
   		 	"group_by_brand_id": {
     		 	"terms": {
      		 	 "field": "store_sales.item.i_brand_id",
            "order" : { "_term" : "asc" }, "size": 100000
      		         },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "store_sales.ss_ext_sales_price"
         }}}}}}}
       }
     }
   }
  }
        }
		}
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/time/resultados/query7.txt
