#!/bin/bash
curl -XPOST 'localhost:9200/i_time/time/_search?pretty' -d '
{ 
  "query": {
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "store_sales",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"term" : {"store_sales.s_state":"TN"}},
                  {"term": {"store_sales.date.d_year":2001}},  
		{"term": {"store_sales.customer.cd_gender":"F"}},{"term": {"store_sales.customer.cd_marital_status":"S"}},{"term": {"store_sales.customer.cd_education_status":"Secondary"}}                 
                ]
               }
              }
            }
          }
        }
      }
    }
  },
   "aggs": {
    "store_sales": {
      "nested": {
        "path": "store_sales"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"term" : {"store_sales.s_state":"TN"}},
                  {"term": {"store_sales.date.d_year":2001}},  
		{"term": {"store_sales.customer.cd_gender":"F"}},{"term": {"store_sales.customer.cd_marital_status":"S"}},{"term": {"store_sales.customer.cd_education_status":"Secondary"}}       
                ]
               }
			   },
          "aggs": {
   		 "group_by_item_id": {
     		 "terms": {
      		  "field": "store_sales.item.i_item_id",
            "order" : { "_term" : "asc" }, "size": 100
            },
            "aggs": {
   		 	"group_by_s_state": {
     		 	"terms": {
      		 	 "field": "store_sales.s_state",
            "order" : { "_term" : "asc" }
      		         },
			"aggs": {
    			"agg4": {
    			  "sum": {
     		        "field": "store_sales.ss_sales_price"
         }}}
       }
     }
   }
  }
        }
		}
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/time/resultados/query4.txt
