#!/bin/bash
curl -XPOST 'localhost:9200/i_date/date/_search?pretty' -d '
{
  "query": {
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "store_sales",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [
				{"term": {"store_sales.s_store_name":"ese"}},
		{"term": {"store_sales.customer.hd_dep_count":3}}, 
                  {"term": {"store_sales.time.t_hour":12}},
				   {"range": {"store_sales.time.t_minute":{"gte":30}}}  
                ]
               }
              }
            } 
      }
    }
   }}},
   "aggs": {
    "store_sales": {
      "nested": {
        "path": "store_sales"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
				{"term": {"store_sales.s_store_name":"ese"}},
		{"term": {"store_sales.customer.hd_dep_count":3}}, 
                  {"term": {"store_sales.time.t_hour":12}},
				   {"range": {"store_sales.time.t_minute":{"gte":30}}}     
                ]
               }
			   }
        }
		}
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/date/resultados/query11.txt
