#!/bin/bash
curl -XPOST 'localhost:9200/i_date/date/_search?pretty' -d '
{
  "query": {"filtered":{ "filter":{
  "bool": {
	      "must": [
		{"term": {"d_year":2001}}, 
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "store_sales",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"range": {"store_sales.item.i_current_price":{"gt":9}}}
                ]
               }
              }
            }
          }
        }
      }
    }
   }]}}}},
   "aggs": {
    "store_sales": {
      "nested": {
        "path": "store_sales"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"range": {"store_sales.item.i_current_price":{"gt":9}}}
                ]
               }
			   },
   "aggs": {
   		 "group_by_state": {
     		 "terms": {
      		  "field": "store_sales.customer.ca_state",
            "order" : { "_term" : "asc" }, "size": 10000
            }
        }
		}
  }}}
}, "size":0
}' -o /home/raphael/Documentos/benchmarktpc/elastic/date/resultados/query2.txt
